controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api:
    prefix: /api
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute
api_authentication:
    path: /api/authentication

api_graphql_entrypoint:
    path: /api/graphql
    controller: api_platform.graphql.action.entrypoint
graphiql:
    path: /api/graphiql
    controller: api_platform.graphql.action.graphiql